### ISSUE TITLE
Connection lost - EHOSTUNREACH

### ISSUE THREAD

**Issue by michib-xx** [jonaseickhoff/musiccast2mqtt#1]
Hello,

on a regular basis, my musiccast2mqtt instance loses connection to the configured MC devices. An example log entry then reads as

```
2021-08-15T02:51:07.608Z [Error] Error SendGetToDevice ip: '10.0.0.xx' error: 'Error: connect EHOSTUNREACH 10.0.0.xx:80'
2021-08-15T02:51:07.612Z [Error] Küche: Error update netusb playinfo. Error: Error: connect EHOSTUNREACH 10.0.0.xx:80
```

When restarting the container, all works fine for some days, until the error appears again. All device were online all the time are reachable even when musiccast2mqtt gives these errors.

Is there any way to automatically recover connection?

Cheers
Micha

**Comment by jonaseickhoff** [comment]
Hi,

this is very strange behavior, because the bridge is just calling the musiccast http api. And for each http call a new connection is made. So there is nothing like recover connection for http. 

Is the connection lost to all devices at once or is this time by time?
